# Generated by Django 5.2.6 on 2025-10-01 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_colegio', '0002_pregunta_testvocacional_opcionrespuesta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opcionrespuesta',
            name='texto',
            field=models.CharField(max_length=400),
        ),
    ]
