# Generated by Django 5.2.6 on 2025-10-01 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_colegio', '0004_paralelo_estudiante_profesor_paralelo_profesor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='rol',
        ),
        migrations.AddField(
            model_name='usuario',
            name='estudiante',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario', to='back_colegio.estudiante'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='profesor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario', to='back_colegio.profesor'),
        ),
    ]
