# Generated by Django 5.2.6 on 2025-10-01 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_colegio', '0005_remove_estudiante_usuario_remove_profesor_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('estudiante', 'Estudiante'), ('docente', 'Docente'), ('admin', 'Administrador')], default='estudiante', max_length=30),
        ),
    ]
