# Generated by Django 5.2.6 on 2025-10-02 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_colegio', '0006_usuario_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='paralelo',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='nombre',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_estudiante_usuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profesor',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_profesor_usuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='estudiante',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiante', to='back_colegio.estudiante'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='profesor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profesor', to='back_colegio.profesor'),
        ),
    ]
