# Generated by Django 5.2.6 on 2025-10-02 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_colegio', '0007_remove_estudiante_apellido_remove_estudiante_nombre_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='usuario',
        #     name='estudiante',
        # ),
        # migrations.RemoveField(
        #     model_name='usuario',
        #     name='profesor',
        # ),
        migrations.AddField(
            model_name='estudiante',
            name='paralelo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paralelo_estudiante_usuario', to='back_colegio.paralelo'),
        ),
    ]
