# Generated by Django 5.2.6 on 2025-10-03 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_colegio', '0009_remove_usuario_estudiante_remove_usuario_profesor_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='usuario',
        #     name='estudiante',
        # ),
        # migrations.RemoveField(
        #     model_name='usuario',
        #     name='profesor',
        # ),
        migrations.CreateModel(
            name='Estudiante_test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completo', models.FloatField(default=0.0, help_text='Porcentaje completado del test (0 a 100)')),
                ('estudiante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiante_take_test', to='back_colegio.estudiante')),
                ('testvocational', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_vocational', to='back_colegio.testvocacional')),
            ],
        ),
    ]
