# Generated by Django 5.2.6 on 2025-10-04 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_colegio', '0010_remove_usuario_estudiante_remove_usuario_profesor_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='testvocacional',
        #     name='fecha_creacion',
        # ),
        # migrations.RemoveField(
        #     model_name='usuario',
        #     name='estudiante',
        # ),
        # migrations.RemoveField(
        #     model_name='usuario',
        #     name='profesor',
        # ),
    ]
