# Generated by Django 5.2.6 on 2025-10-13 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_colegio', '0014_token_remove_testvocacional_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calificaciones',
            name='nota',
        ),
        # migrations.RemoveField(
        #     model_name='testvocacional',
        #     name='fecha_creacion',
        # ),
        # migrations.RemoveField(
        #     model_name='usuario',
        #     name='estudiante',
        # ),
        # migrations.RemoveField(
        #     model_name='usuario',
        #     name='profesor',
        # ),
        migrations.AddField(
            model_name='calificaciones',
            name='notas1',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='calificaciones',
            name='notas2',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='calificaciones',
            name='notas3',
            field=models.FloatField(default=0),
        ),
    ]
