# Generated by Django 5.2.6 on 2025-10-13 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_colegio', '0015_remove_calificaciones_nota_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='testvocacional',
        #     name='fecha_creacion',
        # ),
        # migrations.RemoveField(
        #     model_name='usuario',
        #     name='estudiante',
        # ),
        # migrations.RemoveField(
        #     model_name='usuario',
        #     name='profesor',
        # ),
    ]
