# Generated by Django 5.2.6 on 2025-10-13 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_colegio', '0016_remove_testvocacional_fecha_creacion_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='testvocacional',
        #     name='fecha_creacion',
        # ),
        # migrations.RemoveField(
        #     model_name='usuario',
        #     name='estudiante',
        # ),
        # migrations.RemoveField(
        #     model_name='usuario',
        #     name='profesor',
        # ),
        #  migrations.RemoveField(
        #     model_name='calificaciones',
        #     name='nota',
        # ),
    ]
