# Generated by Django 5.2.6 on 2025-10-28 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_colegio', '0017_remove_testvocacional_fecha_creacion_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='testvocacional',
        #     name='fecha_creacion',
        # ),
        # migrations.RemoveField(
        #     model_name='usuario',
        #     name='estudiante',
        # ),
        # migrations.RemoveField(
        #     model_name='usuario',
        #     name='profesor',
        # ),
        migrations.AlterField(
            model_name='materia',
            name='profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materia', to='back_colegio.profesor'),
        ),
    ]
