# Generated by Django 5.2.6 on 2025-11-01 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_colegio', '0018_remove_testvocacional_fecha_creacion_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='testvocacional',
        #     name='fecha_creacion',
        # ),
        # migrations.RemoveField(
        #     model_name='usuario',
        #     name='estudiante',
        # ),
        # migrations.RemoveField(
        #     model_name='usuario',
        #     name='profesor',
        # ),
        # migrations.AlterField(
        #     model_name='opcionrespuesta',
        #     name='estudiante',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='back_colegio.estudiante'),
        # ),
        migrations.AlterUniqueTogether(
            name='opcionrespuesta',
            unique_together={('pregunta', 'estudiante')},
        ),
    ]
