# Generated by Django 5.2.6 on 2025-11-01 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_colegio', '0019_remove_testvocacional_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='opcionrespuesta',
            unique_together=set(),
        ),
        # migrations.RemoveField(
        #     model_name='testvocacional',
        #     name='fecha_creacion',
        # ),
        # migrations.RemoveField(
        #     model_name='usuario',
        #     name='estudiante',
        # ),
        # migrations.RemoveField(
        #     model_name='usuario',
        #     name='profesor',
        # ),
    ]
