# Generated by Django 5.2.6 on 2025-11-01 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_colegio', '0020_alter_opcionrespuesta_unique_together_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='testvocacional',
        #     name='fecha_creacion',
        # ),
        # migrations.RemoveField(
        #     model_name='usuario',
        #     name='estudiante',
        # ),
        # migrations.RemoveField(
        #     model_name='usuario',
        #     name='profesor',
        # ),
        migrations.AlterUniqueTogether(
            name='opcionrespuesta',
            unique_together={('pregunta', 'estudiante')},
        ),
    ]
