# Generated by Django 5.2.6 on 2025-11-02 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_colegio', '0021_remove_testvocacional_fecha_creacion_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='testvocacional',
        #     name='fecha_creacion',
        # ),
        # migrations.RemoveField(
        #     model_name='usuario',
        #     name='estudiante',
        # ),
        # migrations.RemoveField(
        #     model_name='usuario',
        #     name='profesor',
        # ),
        migrations.CreateModel(
            name='Aptitudes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aptitudes', models.JSONField(default=dict)),
                ('estudiante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aptitudes_Estudiante', to='back_colegio.estudiante')),
            ],
        ),
    ]
